spring:
  mail:
    host: smtp.163.com
    username: gstszbc@163.com
    password: 123456789 #ÄãµÄÓÊÏäÊÚÈ¨Âë
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

